# This file was generated by GoReleaser. DO NOT EDIT.
cask "composed" do
  version "0.5.0"

  on_macos do
    on_intel do
      url "https://github.com/docker-x/composed/releases/download/v#{version}/composed_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/docker-x/composed"
      sha256 "9523e52a3d25ab85ceb8aff4785f32939048272a26ade7dd388ece8e33c3c830"
    end
    on_arm do
      url "https://github.com/docker-x/composed/releases/download/v#{version}/composed_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/docker-x/composed"
      sha256 "5ca6e593801e5c805860d781785de152a9ee9c1579fea07a3f95f5768f73c88b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/docker-x/composed/releases/download/v#{version}/composed_#{version}_linux_amd64.tar.gz",
        verified: "github.com/docker-x/composed"
      sha256 "d7d7b600bf6cb8f74affce422246b4f55c4286c8b195589097b3114be7a847fc"
    end
    on_arm do
      url "https://github.com/docker-x/composed/releases/download/v#{version}/composed_#{version}_linux_arm64.tar.gz",
        verified: "github.com/docker-x/composed"
      sha256 "c430c134ccf2d64fd238c13f7eeae2fb7ed2b7b9b971984f6d21e10e6baa1489"
    end
  end

  name "composed"
  desc "Compose anything into a Docker Compose file"
  homepage "https://github.com/docker-x/composed"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "composed"

  zap trash: [
      "~/.config/composed",
    ]

end
