# This file was generated by GoReleaser. DO NOT EDIT.
cask "composed" do
  version "0.3.1"

  on_macos do
    on_intel do
      url "https://github.com/docker-x/composed/releases/download/v#{version}/composed_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/docker-x/composed"
      sha256 "0bfe59bd768ea08e78db48cc0dbc6131f1c6a7850b3be2189507ffdecdb5a1b9"
    end
    on_arm do
      url "https://github.com/docker-x/composed/releases/download/v#{version}/composed_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/docker-x/composed"
      sha256 "1874d7e749df14066688ff77697ec3158c6fdd51393324dc65a2047fd5574109"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/docker-x/composed/releases/download/v#{version}/composed_#{version}_linux_amd64.tar.gz",
        verified: "github.com/docker-x/composed"
      sha256 "270d3e29752b5f6f5024aaf12a048d581f517f560ef73ae491f08b0189c8263e"
    end
    on_arm do
      url "https://github.com/docker-x/composed/releases/download/v#{version}/composed_#{version}_linux_arm64.tar.gz",
        verified: "github.com/docker-x/composed"
      sha256 "45f154f0c270312b80ef935c355624c370b7039366563ffe67a0ba6cd19b102c"
    end
  end

  name "composed"
  desc "Compose anything into a Docker Compose file"
  homepage "https://github.com/docker-x/composed"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "composed"

  postflight do
    system "xattr", "-r", "-d", "com.apple.quarantine", "#{caskroom}"
  end

  zap trash: [
      "~/.config/composed",
    ]

end
