# This file was generated by GoReleaser. DO NOT EDIT.
cask "composed" do
  version "0.4.0"

  on_macos do
    on_intel do
      url "https://github.com/docker-x/composed/releases/download/v#{version}/composed_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/docker-x/composed"
      sha256 "148eafe345e96d04a4122dc7a5ae6af23b68585fa8fe69a443bc19f73271768c"
    end
    on_arm do
      url "https://github.com/docker-x/composed/releases/download/v#{version}/composed_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/docker-x/composed"
      sha256 "d4fff33fb43be5b7ec551c54c41c79c4b67681b01886df17589eccdf3654ab2e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/docker-x/composed/releases/download/v#{version}/composed_#{version}_linux_amd64.tar.gz",
        verified: "github.com/docker-x/composed"
      sha256 "a69e7b69b36a1c0cb69555630ee044523578c6dd610cffc6ee7edcea79fb2c63"
    end
    on_arm do
      url "https://github.com/docker-x/composed/releases/download/v#{version}/composed_#{version}_linux_arm64.tar.gz",
        verified: "github.com/docker-x/composed"
      sha256 "bc9fed4f0a38b27851fad1115ea82e08faf84f94ca26a32ec58d26df736fff5d"
    end
  end

  name "composed"
  desc "Compose anything into a Docker Compose file"
  homepage "https://github.com/docker-x/composed"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "composed"

  zap trash: [
      "~/.config/composed",
    ]

end
